main: com.crazyhoorse961.tbackups.TethaBackup
name: TethaBackups
version: 1.0.0

commands:
  tethabackup:
    usage: /tethabackup <args>
  dropbox:
    usage: /dropbox [token]
  sequence:
    usage: /sequence