
#What should be the folders/files being backuped?
backup-folders:
  - world
  - world_the_end
  - plugins
#How often in ticks the server should do a backup?
#Math like 24 * 3600 isn't allowed
#You should do one everyday
backup-time: 1728000
#What should be the backup name format?
#Placeholders:
# - %date% (Replaces the date YY/MM/DD of the backup)
backup-name: 'backup-%date%' 
#Should the server broadcast a message when a backup is done?
backup-msg-enabled: true
#If the option above is true, what should the message be? 
backup-msg: '&aA backup has been executed!'
#Backups on specific days..
#A check will be executed every 24 hours
#split every day of the week with a ','.
#The counts start from 1, and 1 = Saturday. And so on.
#Leave empty to disable the function
backup-days: '1,3'
#Well, yeah. You can transfer files to a server, if it have SFTP support
#The location of the backups will be /backups/... (still in a .zip)
sftp: 
#If the sftp function is enabled, it won't write files on your local server, but on your other sftp server, it will
  enabled: false
#The port where the plugin should connect
  port: 22
#The host, it could be a server ip, remember that with OVH/KimSufi/SyS, it is their hostname (if you use backup storage)
  host: 0.0.0.0
#The username of the server
  user: testuser
#The password of the user
  password: userpassword
#The path of where the backups should be stored.
#Remember the '/' at the start
  backup-path: /backups/Minecraft
#Don't have SFTP Access? Here we go!
ftp:
  port: 21
  enabled: false
  host: 0.0.0.0
  password: ftppass0001
  backup-path: /backups/Minecraft
  username: Yo
#You can use the SQL Backup function only with SFTP
sql:
  #Should backuping MySQL/MariaDB databases enabled ?
  enabled: false
  #MySQL port
  port: 3306
  #The MySQL host will be the same as the SFTP one...
  #Username of the MySQL database?
  username: root
  #And his password?
  password: banana00
  #Split every database name (CASE sensitive) with a ';'
  databases-to-save: server;website;panel
#DropBox function :) TUTORIAL: http://pastebin.com/2anrAhKU
dropbox:
  enabled: false
  api-key: myapikey
  api-secret: mysecret
  #Leave empty
  access-token: ''
  sequence: ''

